query bestsellersList($list: String!) {
    bestsellersList(list: $list) {
        listName
        books{
            id
            title
            description
            cover
            authors{
                id
                name
                role
            }
        }
    }
}
