query book($id: ID!) {
  book(id: $id) {
    id
    title
    isbn
    isbn13
    cover
    description
    authors{
        id
        name
        role
    }
    publisher
    format
    pages
    average_rating
    ratings_count
  }
}
